export const companies = [
  {
    img: "/Companies/samsung.png",
    name: "FinNova 1",
    sector: "Technology",
    capital: "$8B",
    address: "London",
    financialIndicators: "Stable growth",
    foundedYear: 2007,
    ceo: "Emma Wilson",
    employeesCount: 4124,
    marketShare: 38,
    trends: ["AI", "Cloud"],
    developmentOpportunities: "Entering Asian market",
    realRevenue: "$5.2B",
    projectedRevenue: "$5.5B",
    realExpenses: "$2.1B",
    projectedExpenses: "$2.3B",
    realClients: 150000,
    projectedClients: 160000
  },
  {
    img: "/Companies/Logo (1).png",
    name: "FinNova 2",
    sector: "Healthcare",
    capital: "$5B",
    address: "Silicon Valley",
    financialIndicators: "Rapid expansion",
    foundedYear: 2006,
    ceo: "Jane Doe",
    employeesCount: 9220,
    marketShare: 43,
    trends: ["Big Data", "AR"],
    developmentOpportunities: "Entering Asian market",
    realRevenue: "$4.8B",
    projectedRevenue: "$5.0B",
    realExpenses: "$2.5B",
    projectedExpenses: "$2.7B",
    realClients: 120000,
    projectedClients: 130000
  },
  {
    img: "/Companies/Logo Alternative (1).webp",
    name: "InnoSoft 3",
    sector: "Healthcare",
    capital: "$7B",
    address: "London",
    financialIndicators: "Consistent profit",
    foundedYear: 1999,
    ceo: "John Smith",
    employeesCount: 6882,
    marketShare: 31,
    trends: ["AI", "Cloud"],
    developmentOpportunities: "R&D investment",
    realRevenue: "$6.0B",
    projectedRevenue: "$6.3B",
    realExpenses: "$3.0B",
    projectedExpenses: "$3.2B",
    realClients: 180000,
    projectedClients: 190000
  },
  {
    img: "/Companies/Logo (5).webp",
    name: "CyberSolutions 4",
    sector: "Retail",
    capital: "$9B",
    address: "Tokyo",
    financialIndicators: "Fluctuating",
    foundedYear: 2000,
    ceo: "Olivia Taylor",
    employeesCount: 7336,
    marketShare: 33,
    trends: ["VR", "5G"],
    developmentOpportunities: "Diversification",
    realRevenue: "$7.1B",
    projectedRevenue: "$7.4B",
    realExpenses: "$4.2B",
    projectedExpenses: "$4.5B",
    realClients: 220000,
    projectedClients: 230000
  },
  {
    img: "/Companies/idN1ydmW8s_1742753953840.png",
    name: "NextGen 5",
    sector: "Finance",
    capital: "$7B",
    address: "Paris",
    financialIndicators: "Stable growth",
    foundedYear: 1999,
    ceo: "Robert Brown",
    employeesCount: 3647,
    marketShare: 39,
    trends: ["VR", "5G"],
    developmentOpportunities: "Expansion into Europe",
    realRevenue: "$5.5B",
    projectedRevenue: "$5.8B",
    realExpenses: "$2.8B",
    projectedExpenses: "$3.0B",
    realClients: 140000,
    projectedClients: 150000
  },
  {
    img: "/Companies/Logo (8).webp",
    name: "CyberSolutions 6",
    sector: "Transportation",
    capital: "$10B",
    address: "Silicon Valley",
    financialIndicators: "Consistent profit",
    foundedYear: 1996,
    ceo: "Emma Wilson",
    employeesCount: 6870,
    marketShare: 24,
    trends: ["Big Data", "AR"],
    developmentOpportunities: "Entering Asian market",
    realRevenue: "$8.2B",
    projectedRevenue: "$8.5B",
    realExpenses: "$4.6B",
    projectedExpenses: "$4.8B",
    realClients: 260000,
    projectedClients: 270000
  },
  {
    img: "/Companies/id8YWtEe_u_1742751498546.png",
    name: "TechVision 11",
    sector: "AI Development",
    capital: "$6B",
    address: "Berlin",
    financialIndicators: "Expanding rapidly",
    foundedYear: 2015,
    ceo: "Sophia Green",
    employeesCount: 5200,
    marketShare: 28,
    trends: ["AI", "Machine Learning"],
    developmentOpportunities: "Scaling product offerings",
    realRevenue: "$4.0B",
    projectedRevenue: "$4.4B",
    realExpenses: "$1.9B",
    projectedExpenses: "$2.1B",
    realClients: 110000,
    projectedClients: 120000
  },
  {
    img: "/Companies/Logo (10).webp",
    name: "EcoFuture 12",
    sector: "Green Energy",
    capital: "$12B",
    address: "Amsterdam",
    financialIndicators: "Steady growth",
    foundedYear: 2008,
    ceo: "David White",
    employeesCount: 8900,
    marketShare: 36,
    trends: ["Solar", "Wind"],
    developmentOpportunities: "New government contracts",
    realRevenue: "$10.1B",
    projectedRevenue: "$10.5B",
    realExpenses: "$5.5B",
    projectedExpenses: "$5.9B",
    realClients: 300000,
    projectedClients: 310000
  }
];
